resources:
  - ../../../base

namePrefix: ${REPO_NAME}-

labels:
  - pairs:
      repo: ${REPO_NAME}
    includeSelectors: true

configMapGenerator:
- name: configmap
  literals:
    - ENV=TEST

images:
- name: nginx
  newName: ${IMAGE_NAME}
  newTag: ${IMAGE_TAG}