resources:
  - ../../base

namePrefix: code-

labels:
  - pairs:
      repo: code
    includeSelectors: true

configMapGenerators: # detect if config file, than add this
- name: configmap
  literals:
    - key1=value1

# patchesStrategicMerge:
#   - |
#     apiVersion: calico
#     kine: NetworkPolicy
#     metadata:
#       name: np
#     spec:
#       selector: ...

images:
- name: nginx
  newName: wavingboat121/code
  newTag: d0586ef9d8a61c6cc9abd0ca9f2e7b5c9c170e83