apiVersion: app/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    spec:
      serviceAccount: not-exist
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: container1
        image: nginx:latest
        envFrom:
        - configMapRef:
            name: configmap
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 100m
            memory: 256Mi