# deploy/orgs/bob/kustomize/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: ssaas
  version: 0.1.0
  releaseName: ssaas
  namespace: kustomize-dev
  valuesFile: values.yaml
  # No 'repo' field since the chart is in the same repo
  # No 'chartHome' as it's not a valid field