apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serverless
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/seannguyn/deployment.git"
    targetRevision: main
    path: "deploy"
  destination:
    server: https://kubernetes.default.svc
    namespace: serverless
    # createNamespace: true
  syncPolicy:
    automated:
      prune: true       # Delete old resources no longer in Git
      selfHeal: true    # Restore changes if manually modified in the cluster