apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssaas-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seannguyn/deployment.git
    targetRevision: HEAD
    path: charts/SSaaS
    helm:
      valueFiles:
        - ../../deploy/seannguyn/ssaas/prod 
  destination:
    server: https://kubernetes.default.svc
    namespace: ssaas-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true