resources:
  - ../../../base

namePrefix: python-sample-

labels:
  - pairs:
      repo: python-sample
    includeSelectors: true

configMapGenerators: # detect if config file, than add this
- name: configmap
  literals:
    - key1=value1

images:
- name: nginx
  newName: wavingboat121/python-sample
  newTag: d4b5539f620b7686d8ffa7a44ef67fa05e1a8c53