apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenant }}-{{ .Values.environment }}-app
  labels:
    app: {{ .Values.tenant }}-{{ .Values.environment }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.tenant }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.tenant }}-{{ .Values.environment }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"