apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tenant }}-{{ .Values.environment }}-svc
  labels:
    app: {{ .Values.tenant }}-{{ .Values.environment }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ .Values.tenant }}-{{ .Values.environment }}